schemaVersion: 1
name: flux
description: Flux is a tool for keeping Kubernetes clusters in sync with sources of configuration
homepage: https://fluxcd.io
license: Apache-2.0

archive:
  fetch:
    github_release:
      repo: fluxcd/flux2
      assetName: 'flux_{{.Version | trimPrefix "v"}}_{{.OS}}_{{.Arch}}.tar.gz'
  verify:
    sha256GitHubAsset: 'flux_{{.Version | trimPrefix "v"}}_checksums.txt'

install:
  - extract:
      from: "{{.Archive}}"
      as: src
  - copy:
      from: "{{.Var.src}}/flux"
      to: "{{.InstallDir}}/bin/flux"

test:
  - run:
      cmd: ["{{.InstallDir}}/bin/flux", "--version"]